//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/zm_toxic_house2.html
halflife.wad
liquids.wad
cstrike.wad
de_piranesi.wad
de_aztec.wad
chateau.wad
cs_747.wad
cs_bdog.wad
torntextures.wad
maps/zm_toxic_house2.bsp
maps/zm_toxic_house2.txt
